# test_config_import.py — Run from project root
from src.config import (
    CONFLUENCE_THRESHOLD, HTF_BIAS_MIN_CANDLES, CONFLUENCE_WEIGHTS,
    FVG_MIN_ATR_MULTIPLE, FVG_MAX_AGE_CANDLES, FVG_MIN_DISPLACEMENT_BODY_RATIO,
    FVG_CLUSTER_MAX_GAP, FVG_PARTIAL_FILL_BONUS_RANGE, MIN_FVG_GAP_SIZE,
    MIN_FVG_GAP_SIZE_DEFAULT, CONFLUENCE_DECAY_START, CONFLUENCE_DECAY_RATE,
    ENTRY_SCORE_EXCELLENT, ENTRY_SCORE_GOOD, ENTRY_SCORE_MARGINAL,
    KILLZONE_RANGES,
)

assert MIN_FVG_GAP_SIZE.get("NIFTY") == 3.0, "MIN_FVG_GAP_SIZE overwrite bug!"
assert HTF_BIAS_MIN_CANDLES == 75
assert CONFLUENCE_THRESHOLD == 4.0
print("✅ All config constants loaded successfully!")